FROM java:8
EXPOSE 8888
ADD /target/config-service-0.0.1-SNAPSHOT.jar config-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","config-service.jar"]
