FROM java:8
EXPOSE 8080
ADD /target/email-service-0.0.1-SNAPSHOT.jar email-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","email-service.jar"]
