FROM java:8
EXPOSE 8761
ADD /target/discovery-service-0.0.1-SNAPSHOT.jar discovery-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=peer2","discovery-service.jar"]