FROM java:8
EXPOSE 8081
ADD /target/course-service-0.0.1-SNAPSHOT.jar course-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","course-service.jar"]
