FROM java:8
EXPOSE 8060
ADD /target/gateway-service-0.0.1-SNAPSHOT.jar gateway-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","gateway-service.jar"]
