FROM java:8
EXPOSE 8080
ADD /target/task-service-0.0.1-SNAPSHOT.jar task-service.jar
#RUN bash -c "apt-get update &> /dev/null; exit 0"
#RUN bash -c "apt-get install nano &> /dev/null"
ENTRYPOINT ["java","-jar","task-service.jar"]
